# 模块配置
interval=30
enable_logging=true

# 需要限制的应用包名列表，用英文分号 ; 分隔
# 注意：关键系统组件（如 systemui、settings、miuisystem等）会自动被过滤，无需担心误写
apps_to_restrict=cn.wps.moffice_eng.xiaomi.lite;com.miui.securitymanager;com.miui.cleanmaster;com.miui.screenrecorder;com.xiaomi.market;com.android.deskclock;com.miui.micloudsync;com.lbe.security.miui;com.xiaomi.metoknlp;com.miui.cloudservice;com.xiaomi.account;com.xiaomi.simactivate.service;com.xiaomi.xmsf;com.unionpay.tsmservice.mi;com.miui.guardprovider;com.miui.securityadd;com.miui.packageinstaller;com.xiaomi.xmsfkeeper